### ISSUE TITLE
Basic in Array

### ISSUE THREAD

**Issue by maheshwaran-1343** [MuneesDeepan28/JSTraining#10]
1) Create an empty array.
2) Create an array with only numbers & print it in the console.
3) Create an array with only strings & print it in the console.
4) Create an array with numbers and strings & print it in the console.
5) In the below array, 
   * How we will print the Third and Fifth elements only, without using for loop.
   * How we will add a new element to the end of the array.
   * How we will add a new element to the beginning of the array.
  const myArray = ['h', 'e', 'l', 'l', 'o'];

**Comment by maheshwaran-1343** [comment]
Munees , place a screenshot here and check whether it will print Third & Fifth Element. Third element is **l** and Fifth element is **o**
![InkedScreenshot 2021-06-30 102835_LI](https://user-images.githubusercontent.com/68689275/123904659-7bc4a380-d98e-11eb-95ae-55660115cb8d.jpg)

**Comment by MuneesDeepan28** [comment]
screenshot added,  printed array Third and Fifth elements is l and o
![UntitleXZxd](https://user-images.githubusercontent.com/86399689/124081098-be5aae80-da68-11eb-8726-b94164c70511.png)

**Comment by MuneesDeepan28** [comment]
screenshot added, printed array Third and Fifth elements is l and o
![Untitsdfled](https://user-images.githubusercontent.com/86399689/124104991-6b8cf100-da80-11eb-8142-e83ecce9b992.png)
