### ISSUE TITLE
check Object.entries is needed for you logic

### ISSUE THREAD

**Issue by siva-vnr** [MuneesDeepan28/JSTraining#3]
![image](https://user-images.githubusercontent.com/20816496/123412027-c03af280-d5ce-11eb-9884-79cba585ce5e.png)
check Object.entries is needed for you logic

**Comment by MuneesDeepan28** [comment]
ok anna

**Comment by MuneesDeepan28** [comment]
https://github.com/MuneesDeepan28/JSTraining/blob/Js-Training-1/Js-trainingTask/studentMarkcalculation1.html
Task completed
