### ISSUE TITLE
Do not use hard coded value 

### ISSUE THREAD

**Issue by siva-vnr** [MuneesDeepan28/JSTraining#4]
![image](https://user-images.githubusercontent.com/20816496/123412265-098b4200-d5cf-11eb-9020-0fa1bf8a5efa.png)

**Comment by MuneesDeepan28** [comment]
Ok anna i will change the hard coded value

**Comment by MuneesDeepan28** [comment]
https://github.com/MuneesDeepan28/JSTraining/blob/Js-Training-1/Js-trainingTask/studentMarkcalculation1.html
Task done
