### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by dhineshwaran25** [MuneesDeepan28/JSTraining#6]
![coding standard issues](https://user-images.githubusercontent.com/83215803/123420513-40feec00-d5d9-11eb-9d2f-506bce54178b.png)

Change the code below to proper coding standards:
------------------------------------------------------------    
function pow(x,n)
{​​​​​​​
  let result=1;
  for(let i=0;i<n;i++) {​​​​​​​result*=x;}​​​​​​​
  return result;
}​​​​​​​

let x=prompt("x?",''), n=prompt("n?",'')
if (n<=0)
{​​​​​​​
  alert(`Power ${​​​​​​​n}​​​​​​​ is not supported, please enter an integer number greater than zero`);
}​​​​​​​
else
{​​​​​​​
  alert(pow(x,n))
}​​​​​​​

**Comment by dhineshwaran25** [comment]
Use proper spacing, naming, proper brackets, alignment

**Comment by MuneesDeepan28** [comment]
ok anna here after i will follow it properly

**Comment by sudarshann** [comment]
Simple logic is one link must have only one purpose. 
If its defining a variable just one variable
if its some operation only that one operation

```
var a;
var b = 5;
var c;
c = b;
c = c + 10;
a = b + c;
```

**Comment by dhineshwaran25** [comment]
Reviewed
