### ISSUE TITLE
Simple calculation

### ISSUE THREAD

**Issue by nagarajsuperbotics** [MuneesDeepan28/JSTraining#7]
simple calculation with "**javascript**".
1.get 2 inputs from prompt with number only.
2.print output in console log.
> 1.add two numbers

> 2.subtract two numbers

> 3.multiplication of two numbers

> 4.division of two numbers

> 5.save a result in local variable and also print result in console.

**Comment by MuneesDeepan28** [comment]
ok anna

**Comment by MuneesDeepan28** [comment]
Task Completed

**Comment by MuneesDeepan28** [comment]
https://github.com/MuneesDeepan28/JSTraining/blob/c0e6c09ad7c9aa4b3a770b44e9334cd536ff8673/Js-trainingTask/calculation.html

**Comment by nagarajsuperbotics** [comment]
Its work fine.
![image](https://user-images.githubusercontent.com/84710411/124070613-b5171500-da5b-11eb-9691-629ee39621c6.png)

But still save wrong input data like string.
![image](https://user-images.githubusercontent.com/84710411/124070784-00c9be80-da5c-11eb-97f4-52a4e0d746e7.png)

**add one more option to save correct result only.**
